name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-20.04, windows-2019]
                php: [8.0]
                laravel: [8.*]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    -   laravel: 8.*
                        testbench: 6.*

        name: ${{ matrix.os }} - P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, mysql, mysqli, pdo_mysql, fileinfo
                    coverage: none

            -   name: Install FFmpeg (Ubuntu)
                if: ${{ matrix.os == 'ubuntu-20.04' }}
                run: |
                    sudo apt-get update
                    sudo apt-get install -y --allow-unauthenticated software-properties-common ffmpeg

            -   name: Install FFmpeg (Windows)
                if: ${{ matrix.os == 'windows-2019' }}
                uses: FedericoCarboni/setup-ffmpeg@v1-beta
                id: setup-ffmpeg

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit
                env:
                    FFMPEG_TEMPORARY_FILES_ROOT: ${{ github.workspace }}